# main
name: React App Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build the React app
        run: CI=false npm run build

    
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: Copy build files to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            build/ ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/${{ secrets.AWS_EC2_USER }}/build/
            
      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
              # Update system and install nginx
              sudo apt-get update
              sudo apt-get install -y nginx
              
              # Setup web directory
              sudo mkdir -p /var/www/react
              sudo rm -rf /var/www/react/*
              sudo cp -r /home/${USER}/build/* /var/www/react/
              sudo chmod -R 755 /var/www/react
              
              # Create nginx configuration
              sudo bash -c "cat > /etc/nginx/sites-available/react" << 'EOL'
          server {
              listen 80;
              server_name _;
              root /var/www/react;
              index index.html index.htm;
              
              location / {
                  try_files $uri $uri/ /index.html;
              }
          }
          EOL
              
              # Enable the site and restart nginx
              sudo ln -sf /etc/nginx/sites-available/react /etc/nginx/sites-enabled/
              sudo rm -f /etc/nginx/sites-enabled/default
              sudo nginx -t && sudo systemctl reload nginx
              sudo systemctl enable nginx
          EOF
          
      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Your React app should be accessible at: http://${{ secrets.AWS_EC2_HOST }}"